name: haskell-bootcamp
version: 0.1.0.0
github: "mjdominus-ly/haskell-bootcamp"
license: BSD3
author: "Mark Dominus"
maintainer: "example@example.com"
copyright: "2022 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

ghc-options:
  - -Wall -Werror -Wno-name-shadowing

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/haskell-bootcamp#readme>

library:
  dependencies:
    - base >= 4.7 && < 5
    - vector
  source-dirs: src

tests:
  haskell-bootcamp-test:
    dependencies:
      - base >= 4.7 && < 5
      - haskell-bootcamp
      - tasty
      - tasty-hunit
      - QuickCheck
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
