name: monad-stacking
version: 0.1.0.0
github: "mjdominus/monad-stacking"
license: BSD3
author: "Mark Dominus"
maintainer: "mjd@pobox.com"
copyright: "2022 Mark Dominus"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/mjdominus/monad-stacking#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl

library:
  source-dirs: src

executables:
  monad-stacking-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - monad-stacking

tests:
  monad-stacking-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - monad-stacking
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - QuickCheck
